### PR TITLE
Abstract nbmolviz3d

### PR DESCRIPTION
**Pull request by justinmc**
Like https://github.com/Autodesk/notebook-molecular-visualization/pull/6, will remove frontend code and move it to [its own repo](https://git.autodesk.com/mccandj/nbmolviz3d), but this time for nbmolviz3d.

~~Branched off of https://github.com/Autodesk/notebook-molecular-visualization/pull/6.~~ Merged.

~~Do not merge, as https://github.com/Autodesk/notebook-molecular-visualization/pull/6 needs to go in first, and the npm module needs to be created and public.~~

~~Currently nbmolviz3d is separated here: https://git.autodesk.com/mccandj/nbmolviz3d.  However, it will need to be made open source and published on npm.~~  Here's the open source repo: https://github.com/Autodesk/nbmolviz3d and npm module: https://www.npmjs.com/package/nbmolviz3d

### CODE REVIEW

**Comment by justinmc** [comment]
Sorry for all the name changes, I was messing with a Github bug I found :)

**Comment by justinmc** [comment]
@avirshup Needs review please.

**Comment by avirshup** [comment]
@justinmc - looks good!

Only question - how were you envisioning dealing with the `moldesign-examples` directory here - Is it just a copy of the directory in `molecular-design-toolkit/moldesign/_notebooks`?

**Comment by justinmc** [comment]
@avirshup Good catch!  I totally didn't mean to commit that directory.  No wonder this diff is so big.  I'll remove it.

**Comment by justinmc** [comment]
+188 - 26,038 much better.  Sorry I made you review it with all that craziness in there :)

**Comment by avirshup** [comment]
That's some damn efficient code cleanup :)

**Comment by avirshup** [comment]
Oh and 👍  to merge

**Pull request merged**
